name: Release binary
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date +'%Y-%m-%d %H:%M:%S') >> ${GITHUB_ENV}
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Build static pages
        run: |
          npm install
          npm run build
        working-directory: ./static
      - uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_flags: -v
          binary_name: "remote-serial-port-server"
          ldflags: -X "github.com/iceking2nd/remote-serial-port-server/global.Version=${{ env.APP_VERSION }}" -X "github.com/iceking2nd/remote-serial-port-server/global.BuildTime=${{ env.BUILD_TIME }}" -X github.com/iceking2nd/remote-serial-port-server/global.GitCommit=${{ github.sha }}